### ISSUE TITLE
Is  metrics  are exposed to prometheus ?

### ISSUE THREAD

**Issue by KesavanKing** [cloudfoundry/metric-proxy#3]
Hi Team,

I can see the annotations to scrape metrics in prometheus 
https://github.com/cloudfoundry/metric-proxy/blob/master/config/manifests/500-metric-proxy-deployment.yml#L17-L19

Are you guys exposing any metrics ?

**Comment by heycait** [comment]
Hi @KesavanKing yes we just started exposing a metric for latency: https://github.com/cloudfoundry/metric-proxy/commit/a8076774d5741eae31e64f9e1e818398bb1ade50. This is still a work in progress to completely integrated with cf-for-k8s and include Prometheus.

**Comment by heycait** [comment]
Closing as this is in now
